server:
  port: 8080
  servlet:
    context-path: /
spring:
  thymeleaf:
    mode: HTML
    cache: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://192.168.99.100:3306/blogdb?useUnicode=true&characterEncoding=utf8mb4&passwordCharacterEncoding=utf8
    username: root
    password: root
  jpa:
    show-sql: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
logging:
  config: classpath:log4j2-spring.xml
#management:
#  add-application-context-header: false