server:
  port: 8081
  servlet:
    context-path:
spring:
  thymeleaf:
    mode: HTML
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blogdb?useUnicode=true&characterEncoding=utf8mb4
    username: root
    password: 1234
  jpa:
    show-sql: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  resources:
    static-locations=classpath: /resources/static/css/
  mvc:
    static-path-pattern: /resources/**
#logging:
#  config: classpath:log4j2.xml
management:
  add-application-context-header: false